filter:
    paths:
        - src
        - tests

tools:
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: true
    php_cpd: true
    php_loc: true
    external_code_coverage:
        runs: 1

build:
    environment:
        OPENSSL_CFLAGS: "/usr/local/ssl/include"
        OPENSSL_LIBS: "/usr/local/ssl/lib -lssl -lcrypto"

    before_scripts:
        - sudo apt-get update
        - sudo apt-get install -y openssl libssl-dev
        - openssl version

    nodes:
        analysis:
            tests:
                override:
                    - ./vendor/bin/pest tests --coverage